version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: backend
    networks:
      - nginx_network
      - postgres_network
    restart: always
    env_file: ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4
    depends_on:
      - db

  db:
    image: postgres:14.2
    container_name: db
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
